server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#    hibernate:
#      ddl-auto: validate
  datasource:
      url: jdbc:postgresql://localhost:5432/stocks
flyway:
  sqlMigrationPrefix: V
  sqlMigrationSeparator: __
  sqlMigrationSuffix: .sql
  validateOnMigrate: true
  init-on-migrate: true